### ISSUE TITLE
module "./xregexp" not found from "[...]i18n-for-browser\\node_modules\\xregexp\\xregexp-all.js"

### ISSUE THREAD

**Issue by Spown** [TrigenSoftware/i18n-for-browser#6]
After updating from 0.7.0 to 0.9.7 the library does no longer compile using the same gulp-browserify@0.5.1 as before.
```
Error: module "./xregexp" not found from "█████\\node_modules\\i18n-for-browser\\node_modules\\xregexp\\xregexp-all.js"
    at notFound (█████\node_modules\browserify\index.js:803:15)
    at █████\node_modules\browserify\index.js:754:23
    at █████\node_modules\browser-resolve\index.js:185:24
    at █████\node_modules\resolve\lib\async.js:36:22
    at load (█████\node_modules\resolve\lib\async.js:54:43)
    at █████\node_modules\resolve\lib\async.js:60:22
    at █████\node_modules\resolve\lib\async.js:16:47
    at FSReqWrap.oncomplete (fs.js:166:21)
```

```js
var stream = require('stream'),
    gulp = require('gulp'),
        browfy = require('gulp-browserify'),
        rename = require('gulp-rename'),
        uglify = require('gulp-uglify'),
        gutil = require('gulp-util'),
    defDestDir = './browser_libs/'
;
gulp.task('i18n_for_browser', function() {
    var fakeSrc = stream.Readable({ objectMode: true }),
        nname = "i18n-for-browser.js",
        res = true
    ;
    fakeSrc._read = function () {
        this.push(new gutil.File({
            cwd: "./node_modules",
            base: "i18n-for-browser-loader.js",
            path: "i18n-for-browser-loader.js",
            contents: new Buffer('i18n = require("i18n-for-browser");')
        }))
        this.push(null) //terminates file stream? hangs without
    }
    return fakeSrc
        .pipe(browfy())
        .on("error", function(error) {
            gutil.log(gutil.colors.red(error.stack));
            res = false
            this.emit("end");
        })
        .pipe(rename(nname))
        .pipe(uglify({preserveComments:'license'}))
        .pipe(gulp.dest(defDestDir))
        .on('finish', function(arg) {
            res && gutil.log(`built i18n-for-browser.js -> ${defDestDir+nname}`)
        })
    ;
});
```

**Comment by Spown** [comment]
@0.9.6 does compile ok.
